# Generated by Django 5.1.3 on 2024-12-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('curp', models.CharField(max_length=100)),
                ('fecha_de_nacimiento', models.DateField()),
                ('num_celular', models.PositiveIntegerField()),
                ('rfc', models.CharField(max_length=100)),
                ('id_sucursales', models.PositiveIntegerField()),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
    ]
